---
- name: Install Apache and upload my web page
  hosts: all
  become: yes

  vars:
    source_file: ./mysite/index.html
    destin_file: /var/www/html

  tasks:
  - name: Install Apache web server
    apt: name=apache2 state=present

  - name: Copy Index.html to servers
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache

  - name: Start webserver and make it enable on boot
    service: name=apache2 state=started enabled=yes

  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted
...
